### ISSUE TITLE
Where are we supposed to run this? 

### ISSUE THREAD

**Issue by calebsw83** [pekempy/plex-poster-export#1]
If I run it from the home folder of my server, it adds the poster folders to the same folder ('\'), overwriting them all so that only the last one is available at the end of the script's execution. If I run it in the library's folder, I get this error: 

Traceback (most recent call last):
  File "/home/calebsw83/plex/Movies/PlexPosterExport.py", line 71, in <module>
    runScript()
  File "/home/calebsw83/plex/Movies/PlexPosterExport.py", line 43, in runScript
    posterPath = download(baseurl + videoPoster, token, "poster.png", videoFolder)
  File "/home/calebsw83/.local/lib/python3.10/site-packages/plexapi/utils.py", line 458, in download
    os.makedirs(savepath, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)

not sure what I can do. I feel like I'm so close to getting it working but I just don't know what else to try.

**Comment by rabbethan** [comment]
Replying to an old issue because I had the same problem; leaving it here for the next guy.

Found that the problem was that the script was searching for the path in a Windows format with a backslash (\\) while I'm running my server on Linux which uses a forward slash (/).

I had to change line 40 from
```python
 videoFolder = videoPath.rpartition('\\')[0] + "\\"
``` 
to
```python
            videoFolder = videoPath.rpartition('/')[0]
``` 

Same has to be done on lines 50 and 64 for "shows".

```python
            showFolder = showPath[0] + "\\"
``` 
to
```python
            showFolder = showPath[0]
``` 

and 


```python
                episodePath = episode.locations[0].rpartition('\\')[0] + "\\"
                episodeFile = episode.locations[0][episode.locations[0].rindex("\\")+1:][:-4]
``` 
to
```python
                episodePath = episode.locations[0].rpartition('/')[0]
                episodeFile = episode.locations[0][episode.locations[0].rindex("/")+1:][:-4]

``` 

That fixed me right up.
